### ISSUE TITLE
Don't use eval()

### ISSUE THREAD

**Issue by BattleRattle** [rtshome/pgbabylon#7]
Using `eval()` is always a bad idea, especially with error suppression like in [PhpArray.php](https://github.com/rtshome/pgbabylon/blob/master/src/DataTypes/PhpArray.php#L37):

``` php
@eval("\$r = [{$regs[1]}];");
```

It allows arbitrary code execution and should be considered as serious security issue. Example:

``` php
use PgBabylon\PDO;
use PgBabylon\DataTypes;

$pdo = new PDO('pgsql:dbname=playground', 'user', 'pass');
$pdo->prepare('CREATE TABLE arraytest (array_column varchar[]')->execute();

// Insert PHP-Code
$stmt = $pdo->prepare('INSERT INTO arraytest (array_column) VALUES (:myarray)');
$stmt->execute(['myarray' => DataTypes\PhpArray(['die(foo)'])]);

$stmt = $pdo->prepare('SELECT array_column FROM arraytest');
$stmt->execute();
$stmt->setColumnType('array_column', PDO::PARAM_ARRAY);
// See the PHP-Code getting executed
$stmt->fetch(PDO::FETCH_ASSOC);
```

**Comment by rtshome** [comment]
Thank you for pointing it out. I wrote that as a quick solution to release the Array Type support as soon as possible.

To solve the issue, I wrote a new decoding algorithm, taking inspiration from that of PsycoPg2 Python driver.
As a plus, the new algorithm supports both single dimension and multidimension arrays too :-)
